version: "3"

networks:
  goedge:
    external: false

services:
  mysqld:
    image: mysql:${MYSQL_VERSION}
    container_name: mysqld
    env_file:
      - .env
    networks:
      - goedge
    command:
      - '--skip-log-bin'
    volumes:
      - ./data/db/mysql:/var/lib/mysql:rw
    restart: always

  edge-admin:
    image: icodex/edge-admin:${VERSION}
    container_name: edge-admin
    ports:
      - 7788:7788/tcp
      - 8001:8001/tcp
    env_file:
      - .env
    networks:
      - goedge
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/edge-admin/configs:/usr/local/goedge/edge-admin/configs
      - ./data/edge-api/configs:/usr/local/goedge/edge-admin/edge-api/configs
    restart: always
    depends_on:
      - mysqld

  edge-node:
    image: icodex/edge-node:${VERSION}
    container_name: edge-node
    ports:
      - 80:80/tcp
      - 443:443/tcp
    env_file:
      - .env
    networks:
      - goedge
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/edge-node/cache:/opt/cache
      - ./data/edge-node/configs:/usr/local/goedge/edge-node/configs
    restart: always
    depends_on:
      - edge-admin
      - mysqld
